"""Hand-calculated controls for legacy pure helpers; not Plan 06 qualification.

No main(), checkpoints, dataset loading, training, or source-drive access.
The production helpers are tested directly; expected values are not generated by them.
"""
import numpy as np
import pytest

from scripts.evaluate import auc_score, dice, label_from_probs

pytestmark = pytest.mark.unit


@pytest.mark.parametrize(("pred", "reference", "expected"), [
    pytest.param([1, 1, 0, 0], [1, 1, 0, 0], 1.0, id="perfect"),
    pytest.param([0, 0, 1, 1], [1, 1, 0, 0], 0.0, id="disjoint"),
    pytest.param([1, 0, 1, 0], [1, 1, 0, 0], 0.5, id="one-of-two-overlap"),
    pytest.param([1, 0, 0, 0], [1, 1, 0, 0], 2 / 3, id="missed-voxel"),
    pytest.param([1, 1, 1, 0], [1, 1, 0, 0], 4 / 5, id="extra-voxel"),
    pytest.param([0, 0, 0, 0], [1, 1, 0, 0], 0.0, id="empty-positive"),
])
def test_t_met_dice_hand_counts(pred, reference, expected):
    # Tiny 3D arrays: expected numerator/denominator counted by hand above.
    p = np.array(pred, dtype=bool).reshape(1, 2, 2)
    g = np.array(reference, dtype=bool).reshape(1, 2, 2)
    assert dice(p, g) == pytest.approx(expected)
    if p.any():
        assert dice(g, p) == pytest.approx(expected)
    else:
        assert np.isnan(dice(g, p))


@pytest.mark.parametrize("pred", [[0, 0], [1, 0]])
def test_t_met_negative_reference_is_ineligible_for_positive_dice(pred):
    # Both correct absence and false positive are NaN, not 1 or 0 here.
    assert np.isnan(dice(np.array(pred), np.zeros(2, dtype=bool)))


def test_t_met_parenchyma_and_region_are_distinct():
    reference = np.array([0, 1, 1, 2])
    prediction = np.array([0, 1, 2, 1])
    # Class-1 intersection=1, counts=2+2; organ union unchanged; lesion missed.
    assert dice(prediction == 1, reference == 1) == 0.5
    assert dice(np.isin(prediction, [1, 2]), np.isin(reference, [1, 2])) == 1.0
    assert dice(prediction == 2, reference == 2) == 0.0


@pytest.mark.parametrize(("labels", "scores", "expected"), [
    ([0, 0, 1, 1], [0.1, 0.2, 0.8, 0.9], 1.0),
    ([0, 0, 1, 1], [0.9, 0.8, 0.2, 0.1], 0.0),
    ([0, 0, 1, 1], [0.5, 0.5, 0.5, 0.5], 0.5),
    # Four positive/negative pairs: win + win + tie + loss = 2.5/4.
    ([0, 0, 1, 1], [0.1, 0.5, 0.5, 0.3], 0.625),
])
def test_t_met_auc_pairwise_goldens(labels, scores, expected):
    assert auc_score(labels, scores) == pytest.approx(expected)
    # Permuting the same paired cases cannot change the ranking statistic.
    assert auc_score(labels[::-1], scores[::-1]) == pytest.approx(expected)


@pytest.mark.parametrize("labels", [[], [0, 0], [1, 1]])
def test_t_met_auc_without_both_classes_is_undefined(labels):
    assert np.isnan(auc_score(labels, [0.5] * len(labels)))


def test_t_met_threshold_boundary_and_class_fallback():
    # Each column sums to 1. Equality is included; bg/pancreas tie -> pancreas.
    probs = np.array([[0.25, 0.26, 0.40, 0.20],
                      [0.25, 0.25, 0.40, 0.20],
                      [0.50, 0.49, 0.20, 0.60]])[:, None, None, :]
    original = probs.copy()
    np.testing.assert_array_equal(label_from_probs(probs, 0.5).ravel(), [2, 0, 1, 2])
    np.testing.assert_array_equal(label_from_probs(probs, 0.6).ravel(), [1, 0, 1, 2])
    np.testing.assert_array_equal(probs, original)
